export enum ROUTES {
    start = 'start',
    help = 'help',
    generate = 'generate',
    brodcast = 'start_broadcast',
    digest = 'start_didgest',
    adminPanel = 'admin_panel',
    generatorMoreData = 'generatorMoreData',
    getLink = 'getLink',
    getInvite = 'getInvite',
    generateQr = 'generateQr',
    getStories = 'getStories',
    generateAvatar = 'generateAvatar',
    avatarCenter = 'avatar-center',
    avatarRound = 'avatar-round',
    avatarLeft = 'avatar-left',
    avatarRight = 'avatar-right',
    message = 'message',
}
