name: Build Docker Image and Push to Evolution Artifact Registry

on:
    push:
        branches: ['main']
env:
    CR_URI: mnikolashin.cr.cloud.ru
    CR_REP: pc_referral_bot
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Evolution Artifact Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.CR_URI }}
                  username: ${{ secrets.EVO_CR_LOGIN }}
                  password: ${{ secrets.EVO_CR_PWD }}

            - name: Build and push docker image to Evolution Aritfact Registry
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ${{ env.CR_URI }}/${{ env.CR_REP }}:${{ github.sha }}
                  file: ./Dockerfile
                  context: ./
